#-------------------------------
# Site Settings
title: Cornelia
logo: # You can add own logo. For example '/images/logo.png'.
description: An impressive portfolio theme for Jekyll
color_scheme: auto # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.

#-------------------------------
# Author Global Settings
author:
    author_name: Jesse Parker
    author_role: Product Designer
    author_description: When I'm not a Product Designer, I can often be found cycling through picturesque landscapes, immersing myself in the joy of two-wheeled adventures. Reading books is another passion of mine, as I love delving into captivating stories and exploring new ideas. Beyond these pursuits, I relish engaging in various activities that nurture my creativity and keep me inspired.
    author_avatar: '/images/01-1.jpg'

#-------------------------------
# Navigation Settings
menu_settings:
    menu_items:
        - title: 'Home'
          url: '/'
        - title: 'About'
          url: '/about/'

# Call to action button
cta_button:
    enable: false
    cta_button_link: '/contact/'
    cta_button_text: Get in touch

#-------------------------------
# Hero Settings
hero:
    enable: true
    hero_intro: Hi, ich bin Cornelia
    hero_title: UX Designerin mit Fokus auf klare Flows
    hero_description: 'Gute UX ist für mich: weniger Reibung, mehr Vertrauen, spürbar bessere Interaktionen. Ich verbinde Nutzerbedürfnisse mit Business-Zielen und übersetze Insights in robuste Konzepte, UI-Systeme und klickbare Prototypen.'
    hero_images:
        - alt: 'Hobby'
          url: '/images/hero-1.jpg'
        - alt: 'Apartment'
          url: '/images/hero-2.jpg'
        - alt: 'Friends'
          url: '/images/hero-3.jpg'
        - alt: 'Workflow'
          url: '/images/hero-4.jpg'

#-------------------------------
# Newsletter
mailchimp:  # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp__input__text: Your email address
mailchimp__button__text: Subscribe

#-------------------------------
# Projects Settings
projects:
    enable: true
    projects_title: Work

#-------------------------------
# Testimonials Section
testimonials:
    enable: true
    testimonials_title: See what our customers are saying

testimonials_items:
    - name: 'Lucas Parker'
      image: '/images/client-1.jpg'
      designation: 'Web Developer'
      content: "If you're looking for a top-notch product designer, look no further. His ability to merge creativity with functionality is remarkable."
      link: 'https://twitter.com/'
      icon: 'fa-brands fa-twitter'
      icon_color: '#1da1f3'

    - name: 'Olivia Williams'
      image: '/images/client-2.jpg'
      designation: 'Data Analyst'
      content: 'His attention to every minute detail ensured that our products stand out, capturing the attention of potential customers.'
      link: 'https://twitter.com/'
      icon: 'fa-brands fa-twitter'
      icon_color: '#1da1f3'

    - name: 'Ava Martinez'
      image: '/images/client-3.jpg'
      designation: 'Designer'
      content: 'The designer brought fresh ideas and innovative solutions to our project, delivering results that exceeded our expectations.'
      link: 'https://twitter.com/'
      icon: 'fa-brands fa-twitter'
      icon_color: '#1da1f3'

    - name: 'Evelyn Turner'
      image: '/images/client-4.jpg'
      designation: 'Data Scientist'
      content: "Exceptional talent! The designer was instrumental in crafting our brand's identity, infusing it with authenticity and personality."
      link: 'https://instagram.com/'
      icon: 'fa-brands fa-instagram'
      icon_color: '#e1306c'

    - name: 'Oliver Davis'
      image: '/images/client-5.jpg'
      designation: 'Software Engineer'
      content: 'Working with the designer was a breath of fresh air! His communication, timeliness, and creative flair were unparalleled.'
      link: 'https://facebook.com/'
      icon: 'fa-brands fa-facebook-f'
      icon_color: '#1977f3'

    - name: 'Isabella Lee'
      image: '/images/client-6.jpg'
      designation: 'QA Engineer'
      content: 'His expertise in web design and branding elevated our online presence, attracting more visitors and increasing our conversions.'
      link: 'https://twitter.com/'
      icon: 'fa-brands fa-twitter'
      icon_color: '#1da1f3'

    - name: 'James Wright'
      image: '/images/client-7.jpg'
      designation: 'Data Analyst'
      content: 'Jessy brought fresh ideas and innovative solutions to our project, delivering results that exceeded our expectations.'
      link: 'https://facebook.com/'
      icon: 'fa-brands fa-facebook-f'
      icon_color: '#1977f3'

    - name: 'Layla Foster'
      image: '/images/client-8.jpg'
      designation: 'CEO'
      content: "I can't thank Jessy enough for their outstanding UI/UX design services. He took our app's user experience to new heights."
      link: 'https://twitter.com/'
      icon: 'fa-brands fa-twitter'
      icon_color: '#1da1f3'

    - name: 'Emily Collins'
      image: '/images/client-9.jpg'
      designation: 'DevOps'
      content: 'Simply outstanding! The designer helped us turn our vague concept into a fully functional and visually stunning app.'
      link: 'https://instagram.com/'
      icon: 'fa-brands fa-instagram'
      icon_color: '#e1306c'

#-------------------------------
# Blog Section
blog:
    enable: true
    blog_title: Writing

#-------------------------------
# Author Section Settings
author_section:
    enable: true
    author_section_role: User Experience Designerin
    author_section_title: Wenn ich nicht designe
    author_section_description: Wenn ich nicht an Interfaces und Flows sitze, bin ich meist auf der Suche nach kleinen Momenten, die mich inspirieren. Ich mag Malen, weil ich dabei frei denken kann und ganz nebenbei neue Perspektiven finde. Yoga gehört für mich dazu, um ruhig zu werden und neue Energie zu sammeln. Sobald die Sonne rauskommt, bin ich gern draußen, das ist für mich der beste Akku. Und ich probiere gerne neue Rezepte aus, um am Ende etwas Gutes auf den Tisch bringen.
    author_section_image: '/images/01.jpg'
    author_section_button_text: co.jessner@gmail.com
    author_section_button_link: 'mailto:co.jessner@gmail.com'

#-------------------------------
# Tags Section Settings
tags_section:
    enable: true
    tags_section_title: Explore our topics

#-------------------------------
# Gallery Section Settings
gallery:
    enable: true
    gallery_title: The Best Moments
    gallery_images:
        - alt: 'Rest'
          url: '/images/gallery-1.jpg'
        - alt: 'City'
          url: '/images/gallery-2.jpg'
        - alt: 'Hobby'
          url: '/images/gallery-3.jpg'
        - alt: 'Car'
          url: '/images/gallery-4.jpg'
        - alt: 'Hobby'
          url: '/images/gallery-5.jpg'
        - alt: 'Lifestyle'
          url: '/images/gallery-6.jpg'

#-------------------------------
# Footer Settings

# Social links
social:
    - { icon: 'fa-brands fa-linkedin', link: 'https://www.linkedin.com/in/corneliajessner/' }
    - { icon: 'fa-brands fa-behance', link: 'https://www.behance.net/corneliajessner' }


# Example of adding a new link to the footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Contact Settings
contact:
    email: your@email.com # Add your form_id
    description: Nuntu comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Nuntu theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test

#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
